<?php
//
// File writer utility
// Dynamically write files from provided data to a server cache.
// UUIDs suffixes for files are generated by uuid_generator script 
// available at http://www.somacon.com/p113.php (copy script text)
// 
// Call with this URL with a returning Ajax request:
// http://[your.server]/[path.to]/file_writer.php?prj=[your.project]
// &out=[output.dir]&data=[raw.encoded.data.to.write]&ext=[file.extension]
// 
// Copyright (c) 2009 Sam Saint-Pettersen.
// 
// Released under the MIT license.
//
require_once "uuid_generator.php";

function fileWriter($prj, $out, $src, $data, $ext) {
	// Generate UUID suffix for file
	$uuid = uuid();
	// When all parameters are passed when invoking...
	if($prj != null or $out != null or $src != null or $data != null or $ext != null) {
		// Write out the file to the output folder
		$fh = fopen($prj . $out . $src . '_' . $uuid . '.' . $ext, 'w');
		fwrite($fh, str_replace('\\', '', rawurldecode($data))); 
		fclose($fh);
		// Return relative path to calling code (echo)
		echo $out . $src . '_' . $uuid . '.' . $ext;
	// Otherwise, return insufficient parameters message to calling code (echo)
	} else echo 'Error: Insufficient parameters given.';
}
fileWriter($_GET['prj'], $_GET['out'], $_GET['src'], $_GET['data'], $_GET['ext']);
?>
