// Hashtag search (hashtags.org)
// generated by create search command
// No need to put in the '#'character
// Public domain
CmdUtils.makeSearchCommand({
  name: "hashtag",
  url: "http://hashtags.org/search?q=%23{QUERY}&page=1",
});

